### ISSUE TITLE
wsのネットワーク接続ができない

### ISSUE THREAD

**Issue by 400time** [uchidalab/Server-setting-repository#7]
担当しているws05がnvidia-smiが通らないので，driverを再インストールを行いたかったが，ネットが繋がらない．
再起動やLANケーブルを抜き差ししても変わらず．

**Comment by naivete5656** [comment]
server roomでも繋がっているwork stationはあるから，おそらく新しいルータを認識できてないとかじゃないかな？
LAN抜き差しや再起動でだめなら，IP を固定IPから一度DHCPに戻してみて．
もし，どうしてもネットに繋がらなかったら最悪，OSの再インストールしかないと思う．

**Comment by naivete5656** [comment]
研究室内の問題であり，研究室のネットが治ると回復した
