### ISSUE TITLE
Dockerfileをbuildする際に不明なエラーが出る

### ISSUE THREAD

**Issue by naivete5656** [uchidalab/Server-setting-repository#8]
localではbuildが通るのにworkstation上でbuildすると
```
Get https://registry-1.docker.io/v2/: dial tcp: lookup registry-1.docker.io: no such host
```
とでてbuildできない

**Comment by naivete5656** [comment]
このサイトに書いてあることは一通り試したが，結局解決できていない．
https://stackoverflow.com/questions/46036152/lookup-registry-1-docker-io-no-such-host

**Comment by naivete5656** [comment]
ルータのDNSが設定されておらず生じたエラーだった．
ルータの設定を変更したところ治った

**Comment by Takeshiddd** [comment]
設定方法はこちらに書いてある。
https://github.com/uchidalab/Server-setting-repository/issues/10
